### PR TITLE
v1.2.0

### LINKED ISSUE #43: Enable config.yml for seperate jail fixed config
It would be nice if we could give every jail-config its own config.yml file and load those together with the main config.yml

This would enable us to seperate "user facing" config like usernames, ip-settings, passwords etc, from "internal only" config like "pkgs".

It would also allow us to more easily push changes to the pkgs required and upGRADE packages with updates.

### LINKED ISSUE #89: Enhancement: Creation of portsnap directed by jails/JAILNAME/config.yml
Currently, portsnap is created and mounted into a jail by default, whether it is useful there or not.

I suggest to instead, introduce a parameter that can be specified globally (default) and overridden on a per-jail basis, via config.yml, on whether to install portsnap at all.

Likely also useful: A parameter to determine which ports to install, if portsnap is being brought in.

This might all already be in flight and I am just catching an in-between half-finished build.

### LINKED ISSUE #91: Mariadb root password not correctly set on install
It seems under some circumstances, the mariadb root password doesn't actually get set correctly on install. 
Changing this from `UPDATE ` to `ALTER` should fix this issue.

### LINKED ISSUE #93: Silent failure of phpmyadmin install with MariaDB blueprint
When installing a mariadb jail, it might fail to correctly install phpmyadmin without any warning.

This happens when `cert_email` is not set, even though we do not require a cert email, caddy has a bug upstream for ages now that enforces the use of cert_email even without SSL cert.

### LINKED ISSUE #94: Mixed different filetypes for rc.d files.
It seems there are currently 2 ways in-use for rc.d service files:
`*.`
and
`*.rc`

I suggest making sure all of them use `*.rc` so everyone can be sure what the use of said file is.

### LINKED ISSUE #95: Bitwarden: don't require type and rename to db_type
Currently there is a "type" variable that needs to be set.
This should actually have been db_type and not be required in the first place.

It's mostly usefull to use sqlite as db.

### LINKED ISSUE #96: Nextcloud: remove postgresql
We don't currently use postgress, nor do am I expecting to create and maintain a jail for it.

If a maintainer for postgresql support shows up, he/she could figure out himself/herself how to connect it with everying.

besides: It hasn't been tested anyway.

### LINKED ISSUE #97: Nextcloud: remove external database support
We are fully moving to a solution where the databases are setup automatically. It doesn't seem right to maintain quite a lot of code in nextcloud to support external DB's only for nextcloud.

We can leave db_type in, just like with bitwarden, but not do anything with it.

### LINKED ISSUE #98: Nextcloud: Move Certificate selection to single variable
There are currently multiple mutualy-exclusive variables to select a certificate/ssl system.
This should be limited to one, string-type variable and input verification. The current system lead to less ease-of-use

### PR DESCRIPTION
**Pull request by Ornias1993**
This PR includes all Commits that will be known as "v1.2.0".

It's a BIG rewrite of the original code and also includes new principles like seperating Jails from their Blueprints. (and this allowing multiple installs of the same blueprint under different jail names)
This is a big overhaul. It restructures most of the config systems.

* It seperates Jail and Blueprint.
* It introduces config versioning (thus new versions can invalidate outdated config files)
* It allows multiple installs of the same blueprint (previously known as jail)

The Blueprint:
- The install script included in this project.
- Config settings are included with the blueprint, but can be overriden in config.yml

The Jail:
- The actuall jail under FreeNAS, the physical running thing you see in the GUI.
- config is done by the user, no config is included, only an example is included

Also included are a lot bug fixes, such as:
- MariaDB root password is now set correctly (Fixes #91 )
- Caddy now uses a default email adress to prevent silent failure during PHPMyAdmin Install (Fixes #93)

And included are some misc. enhancements:
- Installation of portsnap is now a per-blueprint setting (fixes #89 )
- InfluxDB doesn't install a database anymore by default (Lets install one when needed)
- Made sure all rc.d files use `*.rc` (Fixes #94 )
- Renamed type to db_type and made it optional in bitwarden (Fixes #95 )
- Removal of postgresql from nextcloud (Fixes #96 )
- Removal of external databases from Nextcloud (Fixes #97 )
- Cleaned up certificate/ssl selection variables (Fixes #98 )
- Seperated jail config from blueprint config (For example the pkg lists, Fixes #43)
- Tweaks Plex to enable future Quicksync support
- Moves default jails to "base jail"
- Renames Plexpass to Plex Beta.
- Full rewrite of the Wiki system
- Full redesign of automated testing.
- Lots of documentation updates

Every jail can only have 1 blueprint, but blueprints can be used on multiple jails.

Config versioning is introduced, because the old-config is not forward-compatible and the new config is not backwards compatible. v1.2.0 is a good moment to introduce this, because we are removing pkgs from the jail config (moving to the blueprint config) anyhow.

Besides the above, there are also new features and blueprints added into 1.2.0:
- Adds Unifi (with unifipoller buildin, including support for automatic influxDB DB creation)
- Adds InfluxDB
- Adds shared portsnap, ports directory

All Jails tested working.

### CODE REVIEW

**Comment by Ornias1993** [comment]
Current ETA for 1.2.0 is betreen 15-05-2020 and 01-06-2020

**Comment by Ornias1993** [comment]
I consider 1.2.0 Complete feature wise.
Any documentation additions can be send in by smaller patches (will make a docu-dev branch on merge).

But this is a BIG rewrite. So I would like @thorsteneb @disconn3ct and @colemamd  to test and/or review this.
(I'll add PR description based on included commits later)

**Comment by thorsteneb** [comment]
Update check isn't happy, is this expected?

```
root@freenas[~/jailman]# ./jailman.sh -i plex
Working directory for jailman.sh is: /root/jailman
checking for updates using Branch: multi_install
fatal: ambiguous argument 'origin/multi_install': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by thorsteneb** [comment]
Suggestion: Change install.sh for plex so it notifies user of how to connect to the fresh plex instance, http://<ip-here>:32400/web

**Comment by thorsteneb** [comment]
Suggestion: Document update and upgrade flags in README.md

**Comment by thorsteneb** [comment]
bitwarden won't install: db_password can't be empty. It most certainly isn't empty in global config.yml.

Suggestion: More prominent error message, possibly bold, on the exit conditions in install.sh. "ABORTED - bitwarden install not complete, please review and resolve error message above', or something along those lines.

Suggestion: Can bitwarden work with python 3? Python 2 is EOL.

**Comment by Ornias1993** [comment]
@thorsteneb For new changes please file issues. (tweaks in output info for example)
Review is mostly about new changes, if they break or not...

> bitwarden won't install: db_password can't be empty. It most certainly isn't empty in global config.yml.

Thanks I need to check this one

> no ramdisk specified for plex, continuing without randisk

Oops will fix!

> Update check isn't happy, is this expected?

Forgot to update the branch name, will fix!

**Comment by Ornias1993** [comment]
@thorsteneb Most of your issues are planned to be part of 1.3.0 btw...
https://github.com/Ornias1993/jailman/issues/92

It includes refactor and restructure of the blueprints itself.
Where 1.2.0 just includes a restructure of the files and config.

**Comment by colemamd** [comment]
InfluxDB appears to be working, however unifi is broken. I'm working on it now and will create a PR when done.

**Comment by Ornias1993** [comment]
@colemamd Interesting, I had it working a few days back... :O
Looking forward to your PR :)

**Comment by colemamd** [comment]
So it appears if you don't have ports enabled, there is no /usr/local/etc folder.

**Comment by Ornias1993** [comment]
> So it appears if you don't have ports enabled, there is no /usr/local/etc folder.

It shouldn't mater if thats enabled or not :s

**Comment by Ornias1993** [comment]
> Suggestion: Can bitwarden work with python 3? Python 2 is EOL.

Python is not a dependancy of bitwarden_rs
I think its a dependancy of one of the dependancies, but it isn't used in the actual running bitwarden code. So I doubt it has many security implications.

**Comment by Ornias1993** [comment]
> Update check isn't happy

Is fixed, sorry my mistake.

> Typo, should be ramdisk not randisk

Fixed

Some more constructive feedback for @thorsteneb 

> Change install.sh so it notifies user of how to connect to the fresh plex instance

As I'm going to rewrite them all (mostly standardising exit and entry of the install.sh scripts), this means I'm going to rewrite the last part of all install.sh scripts already for 1.3

> Inform users where media files will live

Same here: I don't want to spend time doing this now, if i'm going to redo it completely in a few weeks.

> Document update and upgrade flags in README.md

There aren't any upgrade or update specific flags afaik?
Anyway: I just pushed the "documentation_dev" branch, so we can merge any documentation updates (that aren't related to updates, but just update the readme) into master without a version update :)

> bitwarden won't install: db_password can't be empty. It most certainly isn't empty in global config.yml

Can you recheck? Code wise it isn't different than other jails and rereading it I don't see any problenm here:
```
DB_PASSWORD="jail_${1}_db_password"
...
if [ -z "${!DB_PASSWORD}" ]; then
...
```
About the 1.3 related changes:
I might push it for 1.2.* if it doesn't contain any changes to the config file... But I cant be sure it won't.

**Comment by thorsteneb** [comment]
> > Document update and upgrade flags in README.md
> 
> There aren't any upgrade or update specific flags afaik?

The -u and -g flags aren't mentioned in Readme.md, under "How to use". A user would need to peek into the source to find out how to update or upgrade a jail.

> > bitwarden won't install: db_password can't be empty. It most certainly isn't empty in global config.yml
> 
> Can you recheck? Code wise it isn't different than other jails and rereading it I don't see any problenm here:

Rechecked. I didn't see an issue in the code either, that's why I mentioned it here.

```
Jail creation completed for bitwarden
db_password can't be empty
```

And the relevant section from global config.yml:

```
  mariadb:
    blueprint: mariadb
    ip4_addr: 192.168.3.98/24
    gateway: 192.168.3.1
    db_root_password: SoSecret
    host_name: mariadb.local

  bitwarden:
    blueprint: bitwarden
    ip4_addr: 192.168.3.97/24
    gateway: 192.168.3.1
        db_jail: "mariadb"
    db_password: "SoSecret"
    admin_token: "SoSecret"
```

**Comment by Ornias1993** [comment]
> The -u and -g flags aren't mentioned in Readme.md, under "How to use". A user would need to peek into the source to find out how to update or upgrade a jail.

FFS, You are right... At least `-u` should've been. Will fix that one.
I'll leave `-g` out of it, because it's not actually doing anything and I don't have a good design for it (yet)...

```
  bitwarden:
    blueprint: bitwarden
    ip4_addr: 192.168.3.97/24
    gateway: 192.168.3.1
        db_jail: "mariadb"
    db_password: "SoSecret"
    admin_token: "SoSecret"
```

The indentation at       `  db_jail: "mariadb"` seems wrong to me....

**Comment by thorsteneb** [comment]
> The indentation at ` db_jail: "mariadb"` seems wrong to me....

And it is. That line and the db_password for nextcloud are using a tab, not spaces. I'm doing a purposeful "I am a user" test, where I am copying config.yml.example and then editing it.

I tested again after fixing the indentation on those two lines, and now bitwarden installs. Recommend fixing the indentation in config.yml.example.

There may be an issue with self-signed cert generation:
```/root/jailman/blueprints/bitwarden/install.sh: line 77: No ssl certificate present, generating self signed certificate: command not found```

https://192.168.3.97/admin is not reachable after install.

**Comment by Ornias1993** [comment]
@thorsteneb Sorry if things seems to go slow, i've been busy last few days.
But I pushed the Readme (add update) and config.yml.example quick-fixes you requested anyway

**Comment by thorsteneb** [comment]
No rush. You're faster than kern2011 :)

**Comment by Ornias1993** [comment]
Okey, I added the descrition to the PR.
Besides the planned rewrites for 1.3.0, I think everything is working as it should and most issues should be limted to typo's.

I've created an issue to check and update all dependancies (pkg settings in the config files basically). Including Bitwarden_rs's python version.

I've added it to 1.3.0 for now, but I might push it earlier as a hotfix release (1.2.1). I'll hold off on it for 1.2.0 for now.

If no body object's, i'll aim for a 15-05-2020 release of 1.2.0

**Comment by Ornias1993** [comment]
Migration documentation has been included. Will merge now.

**Pull request merged**
